import type { Domain } from "@/lib/engine/types";

export interface CardMeaning {
  id: number;
  slug: string;
  name: string;
  keywords: string[];
  coreMeaning: string;
  caution: string;
  action: string;
  coreVariants: string[];
  domainVariants: Record<Domain, string>;
  techniqueSnippets: {
    knighting: [string, string];
    diagonal: [string, string];
  };
}

interface CardBase {
  id: number;
  slug: string;
  name: string;
  keywords: string[];
  coreMeaning: string;
  caution: string;
  action: string;
  domainGeneral: string;
  domainLove: string;
  domainWork: string;
  knighting: [string, string];
  diagonal: [string, string];
}

const CARD_BASES: CardBase[] = [
  { id: 1, slug: "rider", name: "Rider", keywords: ["news", "arrival", "motion"], coreMeaning: "swift movement brings new information into view", caution: "acting before context is complete", action: "respond promptly and confirm facts", domainGeneral: "updates that can change your short-term plan", domainLove: "a message or invitation reactivates emotional momentum", domainWork: "incoming communication opens a practical opportunity", knighting: ["knight links show where the message lands unexpectedly", "a distant card can accelerate this arrival"], diagonal: ["on diagonals, Rider narrates the timeline", "diagonal tension can indicate staggered news"] },
  { id: 2, slug: "clover", name: "Clover", keywords: ["luck", "window", "ease"], coreMeaning: "brief luck offers a manageable opening", caution: "assuming fortune will remain without effort", action: "take the chance while it is available", domainGeneral: "small improvements that only matter if acted on quickly", domainLove: "light-hearted encounters can soften a tense dynamic", domainWork: "a low-risk opportunity that only helps if you move efficiently", knighting: ["knight cards reveal where luck can be applied", "knighting may point to timing-sensitive choices"], diagonal: ["diagonals show where luck intersects obligation", "Clover on a main diagonal can reduce resistance"] },
  { id: 3, slug: "ship", name: "Ship", keywords: ["journey", "trade", "distance"], coreMeaning: "distance and exploration expand options", caution: "drifting without destination", action: "define direction before committing resources", domainGeneral: "movement away from the familiar broadens perspective", domainLove: "emotional distance needs intentional bridge-building", domainWork: "expansion, travel, or broader markets come into focus", knighting: ["knight jumps show where travel impacts outcomes", "a knighted card can mark an external influence"], diagonal: ["diagonals reveal long arcs of movement", "Ship on diagonals suggests unfolding across phases"] },
  { id: 4, slug: "house", name: "House", keywords: ["home", "structure", "security"], coreMeaning: "stability and foundations become central", caution: "overprotecting comfort zones", action: "strengthen routines and boundaries", domainGeneral: "focus on home base, habits, and emotional grounding", domainLove: "security and trust define relationship tone", domainWork: "systems and operational basics need reinforcement", knighting: ["knight cards expose hidden stress around stability", "indirect pressure may affect your foundations"], diagonal: ["diagonals show inherited patterns in family or routine", "House across diagonals highlights long-standing structures"] },
  { id: 5, slug: "tree", name: "Tree", keywords: ["health", "roots", "growth"], coreMeaning: "deep growth unfolds gradually", caution: "expecting immediate proof", action: "commit to steady, restorative pacing", domainGeneral: "your long-term wellbeing strategy matters most now", domainLove: "slow relational growth favors consistency", domainWork: "career development benefits from patient skill-building", knighting: ["knights indicate where growth must adapt", "knighted cards show secondary health factors"], diagonal: ["diagonals map legacy and long-term outcomes", "Tree on diagonals indicates compounding effects"] },
  { id: 6, slug: "clouds", name: "Clouds", keywords: ["uncertainty", "fog", "ambiguity"], coreMeaning: "clarity is partial and conditions are shifting", caution: "making absolute claims too early", action: "name unknowns before choosing direction", domainGeneral: "ambiguity asks for careful pacing and better questions", domainLove: "mixed signals need direct communication", domainWork: "unclear priorities can create avoidable churn", knighting: ["knight cards expose where confusion originates", "jump links may reveal hidden assumptions"], diagonal: ["diagonals show whether confusion is temporary or structural", "Clouds on both diagonals can indicate competing narratives"] },
  { id: 7, slug: "snake", name: "Snake", keywords: ["strategy", "complexity", "desire"], coreMeaning: "strategy and layered motives shape outcomes", caution: "overcomplicating what needs directness", action: "separate signal from social noise", domainGeneral: "a nuanced approach beats blunt force", domainLove: "desire and trust need honest boundaries", domainWork: "politics or complex incentives influence decisions", knighting: ["knight moves mark tactical pivots", "a knighted Snake shows indirect leverage"], diagonal: ["diagonals track complex cause-and-effect", "Snake on diagonals can indicate triangular dynamics"] },
  { id: 8, slug: "coffin", name: "Coffin", keywords: ["ending", "rest", "closure"], coreMeaning: "a cycle closes to make space for renewal", caution: "holding onto what has completed", action: "allow closure and protect recovery time", domainGeneral: "an outdated pattern ready to be released gracefully", domainLove: "old relational scripts may need a clean ending", domainWork: "a process that needs to be retired because it no longer serves the goal", knighting: ["knight links identify what is next after closure", "indirect cards reveal what must be retired"], diagonal: ["diagonals reveal the before-and-after arc", "Coffin on a main diagonal signals meaningful transition"] },
  { id: 9, slug: "bouquet", name: "Bouquet", keywords: ["gift", "charm", "invitation"], coreMeaning: "grace and appreciation open relational doors", caution: "confusing pleasant tone with real alignment", action: "offer gratitude and receive support", domainGeneral: "recognition, goodwill, and the momentum they create", domainLove: "warmth and generosity improve intimacy", domainWork: "public-facing diplomacy creates opportunities", knighting: ["knighting points to where support arrives", "jump links can reveal unexpected allies"], diagonal: ["diagonals show social ripples from generosity", "Bouquet on diagonals can soften hard themes"] },
  { id: 10, slug: "scythe", name: "Scythe", keywords: ["cut", "decision", "sudden"], coreMeaning: "a decisive cut reshapes the landscape quickly", caution: "reactive or harsh decisions", action: "choose cleanly and communicate implications", domainGeneral: "urgent prioritization is required", domainLove: "clear boundaries prevent mixed expectations", domainWork: "rapid decisions can reduce operational drag", knighting: ["knights show downstream consequences of the cut", "jumped cards may signal second-order impacts"], diagonal: ["diagonals reveal where a decision echoes", "Scythe across diagonals indicates irreversible shifts"] },
  { id: 11, slug: "whip", name: "Whip", keywords: ["repetition", "tension", "discipline"], coreMeaning: "repetition can either refine or exhaust", caution: "staying in unproductive cycles", action: "turn friction into intentional practice", domainGeneral: "notice patterns that keep replaying", domainLove: "conflict style matters more than conflict frequency", domainWork: "rework loops need a process reset", knighting: ["knights reveal where the loop can break", "jumped cards identify intervention points"], diagonal: ["diagonals show long-running pattern threads", "Whip on diagonals can mark entrenched dynamics"] },
  { id: 12, slug: "birds", name: "Birds", keywords: ["dialogue", "nerves", "exchange"], coreMeaning: "conversation and anxiety move in tandem", caution: "amplifying rumor or speculation", action: "favor concise, clarifying dialogue", domainGeneral: "communication quality shapes immediate outcomes", domainLove: "small talks and check-ins restore emotional safety", domainWork: "frequent updates reduce uncertainty", knighting: ["knights show where a message needs rerouting", "indirect links can reveal hidden stakeholders"], diagonal: ["diagonals map social echo effects", "Birds on diagonals suggests rapidly spreading narratives"] },
  { id: 13, slug: "child", name: "Child", keywords: ["beginning", "small", "fresh"], coreMeaning: "a new beginning needs light structure", caution: "underestimating complexity", action: "start small and iterate", domainGeneral: "fresh perspective can reset stale assumptions", domainLove: "gentle curiosity can reopen trust", domainWork: "prototype and learn quickly", knighting: ["knight links show where the new start influences others", "jumped cards identify learning opportunities"], diagonal: ["diagonals reveal growth trajectory from early seeds", "Child across diagonals indicates formative momentum"] },
  { id: 14, slug: "fox", name: "Fox", keywords: ["caution", "craft", "self-interest"], coreMeaning: "skillful caution and tactical thinking are required", caution: "hyper-vigilance or distrust", action: "verify details and protect your value", domainGeneral: "discernment prevents avoidable errors", domainLove: "clarify intentions before escalating commitment", domainWork: "quality control and strategic positioning matter", knighting: ["knight cards expose hidden incentives", "jump links flag tactical adjustments"], diagonal: ["diagonals reveal long-range consequences of tactics", "Fox on diagonals emphasizes intelligent restraint"] },
  { id: 15, slug: "bear", name: "Bear", keywords: ["power", "resources", "protection"], coreMeaning: "resource power and stewardship shape the outcome", caution: "control struggles or scarcity fear", action: "use leverage responsibly", domainGeneral: "strength can protect if paired with fairness", domainLove: "security themes influence emotional dynamics", domainWork: "budget, authority, and ownership come forward", knighting: ["knights show where influence can be applied", "jumped cards may reveal power asymmetry"], diagonal: ["diagonals trace resource flow over time", "Bear on diagonals highlights structural influence"] },
  { id: 16, slug: "stars", name: "Stars", keywords: ["guidance", "clarity", "signal"], coreMeaning: "clear guidance and long-range direction emerge", caution: "idealizing without execution", action: "convert vision into steps", domainGeneral: "big-picture alignment and long-range clarity", domainLove: "shared hopes can reorient the relationship", domainWork: "strategy gains clarity and coherence", knighting: ["knights point to where guidance becomes practical", "jump links highlight network effects"], diagonal: ["diagonals reveal long-range pattern alignment", "Stars on diagonals supports coherent planning"] },
  { id: 17, slug: "stork", name: "Stork", keywords: ["change", "upgrade", "move"], coreMeaning: "change is active and potentially beneficial", caution: "constant switching without consolidation", action: "sequence improvements deliberately", domainGeneral: "a healthy update ready to happen", domainLove: "relationship dynamics can evolve constructively", domainWork: "process upgrades and transitions are favored", knighting: ["knights reveal where change propagates", "jump links identify sensitive transition points"], diagonal: ["diagonals show transformation phases", "Stork on diagonals marks migratory momentum"] },
  { id: 18, slug: "dog", name: "Dog", keywords: ["loyalty", "ally", "support"], coreMeaning: "reliable support and trust become key", caution: "assuming loyalty without reciprocity", action: "invest in dependable alliances", domainGeneral: "trusted support and the steadiness it brings", domainLove: "friendship and consistency strengthen intimacy", domainWork: "collaboration with proven allies helps execution", knighting: ["knights reveal where allies can intervene", "jump links may identify overlooked supporters"], diagonal: ["diagonals map trust over time", "Dog on diagonals stabilizes volatile patterns"] },
  { id: 19, slug: "tower", name: "Tower", keywords: ["institution", "distance", "status"], coreMeaning: "structure, authority, and boundaries dominate", caution: "emotional isolation or rigidity", action: "balance professionalism with connection", domainGeneral: "you may need stronger standards and boundaries", domainLove: "distance requires intentional bridge-building", domainWork: "institutional processes and hierarchy matter", knighting: ["knights show where authority influences outcomes", "jump links can expose bureaucratic bottlenecks"], diagonal: ["diagonals reveal long-term structural impact", "Tower across diagonals often marks legacy choices"] },
  { id: 20, slug: "garden", name: "Garden", keywords: ["public", "network", "visibility"], coreMeaning: "public context and community shape momentum", caution: "performing for optics over substance", action: "curate meaningful participation", domainGeneral: "the wider social ecosystem and visible context", domainLove: "the public side of the bond reshaping what happens in private", domainWork: "networking and visibility support progress", knighting: ["knights show where social bridges can help", "jumped cards reveal strategic introductions"], diagonal: ["diagonals map audience response over time", "Garden on diagonals broadens impact"] },
  { id: 21, slug: "mountain", name: "Mountain", keywords: ["obstacle", "delay", "effort"], coreMeaning: "an obstacle demands patient strategy", caution: "assuming delay means failure", action: "work in stages and re-route as needed", domainGeneral: "slower but still viable progress", domainLove: "emotional distance needs patient repair", domainWork: "structural blockers require persistence and planning", knighting: ["knights indicate alternate routes", "jump links show where pressure can be relieved"], diagonal: ["diagonals reveal obstacle timelines", "Mountain on diagonals emphasizes endurance"] },
  { id: 22, slug: "crossroads", name: "Crossroads", keywords: ["choice", "branch", "option"], coreMeaning: "multiple paths require explicit criteria", caution: "analysis paralysis", action: "choose the path aligned with values", domainGeneral: "decision quality now shapes next cycle", domainLove: "relationship direction must be named clearly", domainWork: "strategic forks require tradeoff clarity", knighting: ["knights show secondary consequences of each option", "jump links identify leverage points after choosing"], diagonal: ["diagonals map diverging and converging paths", "Crossroads on diagonals can mark pivotal timing"] },
  { id: 23, slug: "mice", name: "Mice", keywords: ["erosion", "stress", "leak"], coreMeaning: "small drains can undermine major goals", caution: "ignoring minor losses until they accumulate", action: "patch leaks and simplify", domainGeneral: "reduce stressors and prevent gradual depletion", domainLove: "small unresolved tensions can wear trust down", domainWork: "operational leakage needs immediate maintenance", knighting: ["knights expose hidden drains", "jump links reveal where attrition spreads"], diagonal: ["diagonals show attrition patterns over time", "Mice across diagonals indicates compounding stress"] },
  { id: 24, slug: "heart", name: "Heart", keywords: ["love", "values", "devotion"], coreMeaning: "values and emotional truth guide choices", caution: "idealizing without boundaries", action: "speak and act from authentic care", domainGeneral: "alignment with your core values", domainLove: "affection deepens through honest vulnerability", domainWork: "value alignment improves motivation", knighting: ["knights show where emotion can be applied constructively", "jump links may reveal relational turning points"], diagonal: ["diagonals map emotional arcs", "Heart on diagonals often marks meaning-rich developments"] },
  { id: 25, slug: "ring", name: "Ring", keywords: ["commitment", "contract", "cycle"], coreMeaning: "agreements and repeating structures are active", caution: "staying bound to outdated commitments", action: "review terms and renew consciously", domainGeneral: "commitment clarity stabilizes momentum", domainLove: "partnership agreements need intentional upkeep", domainWork: "contracts and recurring obligations shape outcomes", knighting: ["knights indicate where commitments are tested", "jump links reveal terms that need revision"], diagonal: ["diagonals show cyclical patterns", "Ring on diagonals points to long-form commitments"] },
  { id: 26, slug: "book", name: "Book", keywords: ["knowledge", "secrecy", "study"], coreMeaning: "hidden knowledge or learning is central", caution: "withholding critical context", action: "research deeply and disclose responsibly", domainGeneral: "what is not yet visible", domainLove: "private conversations hold key clarity", domainWork: "specialized information offers leverage", knighting: ["knights show where information gaps matter", "jump links identify learning priorities"], diagonal: ["diagonals map revelation timelines", "Book on diagonals indicates layered disclosure"] },
  { id: 27, slug: "letter", name: "Letter", keywords: ["document", "message", "record"], coreMeaning: "written communication and records are decisive", caution: "vague or untracked communication", action: "document clearly and follow up", domainGeneral: "written clarity improves confidence", domainLove: "clear messages prevent avoidable misunderstandings", domainWork: "documentation protects execution quality", knighting: ["knights show where communication must jump channels", "jump links identify critical recipients"], diagonal: ["diagonals reveal the message trail", "Letter on diagonals suggests cascading updates"] },
  { id: 28, slug: "counterpart", name: "Counterpart", keywords: ["other", "mirror", "partner"], coreMeaning: "the significant other perspective enters the reading", caution: "projecting assumptions onto others", action: "clarify roles and expectations", domainGeneral: "consider how the other party experiences this", domainLove: "partnership dynamics require mutual clarity", domainWork: "key counterpart stakeholders shape outcomes", knighting: ["knights show where counterpart influence surfaces indirectly", "jump links reveal hidden relational leverage"], diagonal: ["diagonals map reciprocal dynamics", "Counterpart on diagonals highlights mirrored patterns"] },
  { id: 29, slug: "querent", name: "Querent", keywords: ["self", "identity", "agency"], coreMeaning: "the querent's agency and orientation are central", caution: "self-protective narratives limiting options", action: "choose from values rather than fear", domainGeneral: "your role and boundaries set the tone", domainLove: "self-awareness improves relational clarity", domainWork: "professional identity and priorities need definition", knighting: ["knights show where your influence reaches indirectly", "jump links reveal strategic leverage points"], diagonal: ["diagonals track personal storyline arcs", "Querent on diagonals marks identity shifts"] },
  { id: 30, slug: "lily", name: "Lily", keywords: ["maturity", "peace", "ethics"], coreMeaning: "maturity and principled calm support the path", caution: "passive avoidance of necessary action", action: "pair composure with clear intent", domainGeneral: "steady ethics and long-term judgment", domainLove: "patience and respect improve emotional quality", domainWork: "professional integrity and standards matter", knighting: ["knights show where maturity can de-escalate tension", "jump links identify diplomacy moments"], diagonal: ["diagonals reveal legacy themes", "Lily across diagonals indicates refined outcomes"] },
  { id: 31, slug: "sun", name: "Sun", keywords: ["success", "vitality", "confidence"], coreMeaning: "clarity and momentum increase quickly", caution: "overconfidence without checks", action: "use visibility responsibly", domainGeneral: "energy, confidence, and forward movement", domainLove: "warmth and openness can heal stalled dynamics", domainWork: "recognition and progress are likely if sustained", knighting: ["knights reveal where momentum can be amplified", "jump links indicate spotlight moments"], diagonal: ["diagonals map rising visibility", "Sun on diagonals often signals breakthrough arcs"] },
  { id: 32, slug: "moon", name: "Moon", keywords: ["recognition", "emotion", "cycle"], coreMeaning: "emotional rhythm and recognition influence outcomes", caution: "being led by fluctuating mood", action: "track cycles and communicate needs", domainGeneral: "sensitivity and perception are heightened", domainLove: "emotional attunement is required", domainWork: "reputation and feedback loops matter", knighting: ["knights show where moods affect decisions indirectly", "jump links identify recognition triggers"], diagonal: ["diagonals trace emotional cycles", "Moon on diagonals can indicate reputation arcs"] },
  { id: 33, slug: "key", name: "Key", keywords: ["solution", "certainty", "unlock"], coreMeaning: "a decisive solution becomes accessible", caution: "locking onto one answer too soon", action: "verify then commit", domainGeneral: "a workable solution becoming available through focused action", domainLove: "a clarifying conversation can unlock progress", domainWork: "a strategic fix can remove recurring friction", knighting: ["knights identify where the solution propagates", "jump links show prerequisite steps"], diagonal: ["diagonals reveal when clarity arrives", "Key across diagonals suggests synchronizing opportunities"] },
  { id: 34, slug: "fish", name: "Fish", keywords: ["money", "flow", "commerce"], coreMeaning: "resources and flow patterns become central", caution: "untracked inflow/outflow", action: "monitor movement and align values", domainGeneral: "resource flow is dynamic and responsive", domainLove: "shared resource expectations need clarity", domainWork: "commercial and financial dynamics drive outcomes", knighting: ["knights show where resource flow can be redirected", "jump links reveal hidden financial influences"], diagonal: ["diagonals map liquidity patterns", "Fish on diagonals indicates long-range flow conditions"] },
  { id: 35, slug: "anchor", name: "Anchor", keywords: ["stability", "career", "endurance"], coreMeaning: "long-term commitment and steadiness are highlighted", caution: "staying anchored to obsolete goals", action: "stabilize what matters and release dead weight", domainGeneral: "durability and follow-through that can actually hold", domainLove: "consistency creates relational safety", domainWork: "career direction and sustained effort are central", knighting: ["knights show where stability can be reinforced", "jump links reveal pressure points on endurance"], diagonal: ["diagonals reveal long-term commitment arcs", "Anchor on diagonals indicates durable outcomes"] },
  { id: 36, slug: "cross", name: "Cross", keywords: ["burden", "meaning", "duty"], coreMeaning: "meaningful responsibility asks for wise carrying", caution: "accepting burdens that are not yours", action: "differentiate purpose from pressure", domainGeneral: "a serious theme calls for grounded reflection", domainLove: "emotional burdens require shared processing", domainWork: "duty and accountability are in focus", knighting: ["knights show where burden can be redistributed", "jump links reveal support paths"], diagonal: ["diagonals map purpose and sacrifice themes", "Cross on diagonals marks spiritually significant cycles"] },
];

function buildCoreVariants(card: CardBase): string[] {
  return [
    `${card.name} highlights ${card.coreMeaning}.`,
    `At this stage, ${card.name.toLowerCase()} suggests ${card.action}.`,
    `${card.name} carries the keywords ${card.keywords.join(", ")}, emphasizing ${card.coreMeaning}.`,
    `The gift of ${card.name.toLowerCase()} is that ${card.coreMeaning}, while the caution is ${card.caution}.`,
    `Seen pragmatically, ${card.name.toLowerCase()} points to ${card.action} so momentum can build cleanly.`,
    `${card.name} asks for a grounded response: ${card.action}; avoid ${card.caution}.`,
  ];
}

export const CARD_MEANINGS: CardMeaning[] = CARD_BASES.map((base) => ({
  id: base.id,
  slug: base.slug,
  name: base.name,
  keywords: base.keywords,
  coreMeaning: base.coreMeaning,
  caution: base.caution,
  action: base.action,
  coreVariants: buildCoreVariants(base),
  domainVariants: {
    general: base.domainGeneral,
    love: base.domainLove,
    work: base.domainWork,
  },
  techniqueSnippets: {
    knighting: base.knighting,
    diagonal: base.diagonal,
  },
}));

export const CARD_BY_ID = new Map(CARD_MEANINGS.map((card) => [card.id, card]));
export const CARD_BY_SLUG = new Map(CARD_MEANINGS.map((card) => [card.slug, card]));

export function getCardMeaning(cardId: number): CardMeaning {
  const card = CARD_BY_ID.get(cardId);
  if (!card) {
    throw new Error(`Unknown card id ${cardId}`);
  }
  return card;
}
