"use client";

import { cn } from "@/lib/utils/cn";

interface BrandFooterProps {
  spreadLabel?: string;
  className?: string;
}

export function BrandFooter({ spreadLabel, className }: BrandFooterProps) {
  return (
    <footer
      className={cn(
        "ritual-panel-soft px-4 py-3 text-xs text-[color:var(--theme-muted,var(--brand-muted))]",
        className,
      )}
    >
      <div className="flex flex-wrap items-center justify-between gap-3">
        <p>© 2026 Peter McKay</p>
        <a
          href="https://ko-fi.com/A0A11UE729"
          target="_blank"
          rel="noopener noreferrer"
          className="inline-block min-h-[44px] py-2 underline underline-offset-2 hover:opacity-80"
        >
          Support my Ko-Fi
        </a>
      </div>
      <div className="mt-2 flex flex-wrap items-center justify-between gap-3 border-t border-[color:var(--theme-border,var(--brand-border))] pt-2">
        <p>Generated by 36cards.com</p>
        {spreadLabel ? <p>{spreadLabel}</p> : null}
      </div>
      <p className="mt-2 text-[11px] leading-relaxed text-[color:var(--theme-muted,var(--brand-muted))]">
        For entertainment purposes only. Not medical, legal or financial advice. Make your own life decisions.
      </p>
    </footer>
  );
}
