export interface PdfBrandContext {
  spreadLabel: string;
  generatedAt: string;
}

export function pdfHeaderHtml(ctx: PdfBrandContext): string {
  return `<div style=\"display:flex;justify-content:space-between;align-items:center;padding:10px 14px;border-bottom:1px solid #d7c8b2;background:#f7efe4;\">
    <div style=\"font-family:Manrope,Arial,sans-serif;font-weight:700;font-size:15px;color:#1f1a16;\">36 Cards</div>
    <div style=\"font-family:Manrope,Arial,sans-serif;font-size:11px;color:#5f5042;\">36cards.com - ${ctx.spreadLabel}</div>
  </div>`;
}

export function pdfFooterHtml(ctx: PdfBrandContext): string {
  return `<div style=\"display:flex;justify-content:space-between;align-items:center;padding:8px 14px;border-top:1px solid #d7c8b2;background:#fdfaf5;\">
    <div style=\"font-family:Manrope,Arial,sans-serif;font-size:10px;color:#5f5042;\">Generated by 36cards.com</div>
    <div style=\"font-family:Manrope,Arial,sans-serif;font-size:10px;color:#5f5042;\">${ctx.generatedAt}</div>
  </div>`;
}

export function pdfWatermarkText(): string {
  return "36cards.com";
}
